//HintName: Testing.ParentClass.ParentClass2.TheBadger_EVENT.StringValue.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.EventSourcing.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

#nullable enable

namespace Testing
{
	partial class ParentClass
	{
		partial class ParentClass2
		{
			partial class TestAggregate
			{
				// Property for field: _stringValue
				public System.String? StringValue
				{
					get => _stringValue;
					private set
					{
						if (System.Collections.Generic.Comparer<System.String>.Default.Compare(value, _stringValue) != 0)
						{
							RecordAndApplyEvent(new Testing.ParentClass.ParentClass2.TheBadger_EVENT() { StringValue = value });
						}
					}
				}

				void ApplyStringValue(Testing.ParentClass.ParentClass2.TheBadger_EVENT @event)
				{
					StringValue = @event.StringValue;
		}
			}
		}
	}
}
