//HintName: Testing.StringValueEvent.StringValue.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.EventSourcing.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

#nullable enable

namespace Testing
{
	partial class TestAggregate
	{
		// Property for field: _stringValue
		public string? StringValue
		{
			get => _stringValue;
			set
			{
				if (System.Collections.Generic.Comparer<string>.Default.Compare(value, _stringValue) != 0)
				{
					RecordAndApplyEvent(new Testing.StringValueEvent() { StringValue = value });
				}
			}
		}

		void ApplyStringValue(Testing.StringValueEvent @event)
		{
			StringValue = @event.StringValue;
		}
	}
}
